---
- name: install packages
  with_items: "{{ consul_template_packages }}"
  pkgng:
    name: "{{ item.name }}"
  notify:
    - restart consul-template

- name: create consul-template directories
  with_items: "{{ consul_template_dirs }}"
  file:
    path: "{{ item.name }}"
    state: directory

- name: enable consul-template service
  template:
    src: consul_template.j2
    dest: /etc/rc.conf.d/consul_template
  notify:
    - restart consul-template

- name: configure consul-template service
  template:
    src: consul-template.conf.j2
    dest: /usr/local/etc/consul-template.d/consul-template.conf
  notify:
    - restart consul-template
